import { Tool } from "@/components/ToolCard";

export const categories = [
  "Capacity",
  "Customer",
  "KPI",
  "Maintenance",
  "MRP",
  "OEE",
  "Order",
  "Purchase",
  "QMS",
  "Stock",
  "TMS",
  "SGM",
  "Assembly",
  "Energy",
  "Subcontracting",
  "Pre-Assembly",
  "Test Field",
  "History",
  "Knowledge Graph",
  "UNS",
  "Discovery",
] as const;

export const categoryMeta: Record<string, { label: string; description: string; icon: string }> = {
  Capacity: { label: "Capacity Planning", description: "Machine utilization, load analysis, CM01/CM21", icon: "M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" },
  Customer: { label: "Customer Orders", description: "Order tracking, delivery risk, VA05", icon: "M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" },
  KPI: { label: "KPIs & Revenue", description: "OTD, revenue, delivery performance", icon: "M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" },
  Maintenance: { label: "Maintenance", description: "Notifications, MTBF/MTTR, downtime analysis", icon: "M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.066 2.573c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.573 1.066c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.066-2.573c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" },
  MRP: { label: "Material Planning", description: "MD04, MD07, availability forecasts, shortages", icon: "M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" },
  OEE: { label: "OEE & Production", description: "Availability, performance, quality, scrap history", icon: "M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z" },
  Order: { label: "Work Orders", description: "Order details, machine queues, material readiness", icon: "M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" },
  Purchase: { label: "Purchasing", description: "Open purchases, suppliers, evaluations", icon: "M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 100 4 2 2 0 000-4z" },
  QMS: { label: "Quality Management", description: "SPC alarms, calibration, Cpk, quality notifications", icon: "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" },
  Stock: { label: "Stock & Inventory", description: "Stock levels, reservations, low-stock alerts", icon: "M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" },
  TMS: { label: "Tool Management", description: "Tool wear, replacements, article tool lists", icon: "M11 4a2 2 0 114 0v1a1 1 0 001 1h3a1 1 0 011 1v3a1 1 0 01-1 1h-1a2 2 0 100 4h1a1 1 0 011 1v3a1 1 0 01-1 1h-3a1 1 0 01-1-1v-1a2 2 0 10-4 0v1a1 1 0 01-1 1H7a1 1 0 01-1-1v-3a1 1 0 00-1-1H4a2 2 0 110-4h1a1 1 0 001-1V7a1 1 0 011-1h3a1 1 0 001-1V4z" },
  SGM: { label: "Injection Molding", description: "Process data, cavity balance, trends, aggregates", icon: "M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" },
  Assembly: { label: "Assembly Lines", description: "Station tools, OEE, BDE, process data, maintenance", icon: "M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z" },
  Energy: { label: "Energy Management", description: "Consumption, cost, per-part energy, base load", icon: "M13 10V3L4 14h7v7l9-11h-7z" },
  Subcontracting: { label: "Subcontracting", description: "External processing orders, supplier capacity", icon: "M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4" },
  "Pre-Assembly": { label: "Pre-Assembly", description: "Cell status, OEE, buffer levels, maintenance", icon: "M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" },
  "Test Field": { label: "Test Field", description: "Function tests, leak tests, burn-in, defect analysis", icon: "M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" },
  History: { label: "History", description: "Time-series trends, comparisons, aggregations, anomaly detection", icon: "M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" },
  "Knowledge Graph": { label: "Knowledge Graph", description: "Impact analysis, paths, neighbors, semantic search, schema, Cypher queries, chart generation, delivery snapshots", icon: "M14 10l-2 1m0 0l-2-1m2 1v2.5M20 7l-2 1m2-1l-2-1m2 1v2.5M14 4l-2-1-2 1M4 7l-2-1m2 1l-2 1m2-1v2.5M12 21l-2-1m2 1l2-1m-2 1v-2.5M6 18l-2-1v-2.5M18 18l2-1v-2.5" },
  UNS: { label: "UNS (MQTT)", description: "Live machine data via MQTT: status, values, categories, alerts, comparisons", icon: "M8.111 16.404a5.5 5.5 0 017.778 0M12 20h.01m-7.08-7.071c3.904-3.905 10.236-3.905 14.141 0M1.394 9.393c5.857-5.858 15.355-5.858 21.213 0" },
  Discovery: { label: "Discovery", description: "Auto-discovered machines and sensors from MQTT UNS", icon: "M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" },
};

export const tools: Tool[] = [
  // Capacity (5)
  { name: "factory_get_cm01", description: "Capacity utilization (CM01) for a machine by period (day/week).", category: "Capacity", params: [{ name: "machineNo", required: true }, { name: "periodType", required: false }, { name: "periodCount", required: false }] },
  { name: "factory_get_capacity_overview", description: "Capacity overview of all machines. Identifies over-/under-utilized machines.", category: "Capacity", params: [{ name: "periodType", required: false }, { name: "periodCount", required: false }] },
  { name: "factory_get_capacity_summary", description: "Compact capacity summary of all machines (current + next week).", category: "Capacity", params: [] },
  { name: "factory_get_cm21_orders", description: "Production orders per work center (CM21), filterable by machine.", category: "Capacity", params: [{ name: "machineNo", required: false }] },
  { name: "factory_get_shift_schedule", description: "Shift model for all departments: which shifts run when, net minutes, holidays.", category: "Capacity", params: [{ name: "machineId", required: false }] },
  { name: "factory_get_capacity_load", description: "Average capacity utilization in percent.", category: "Capacity", params: [] },
  // Customer (4)
  { name: "factory_get_customer_orders", description: "Lists all customer orders: customer, article, quantity, delivery dates, status.", category: "Customer", params: [{ name: "status", required: false }] },
  { name: "factory_get_customer_order", description: "Details of a customer order including production order and delivery status.", category: "Customer", params: [{ name: "kundenauftragNr", required: true }] },
  { name: "factory_get_va05_summary", description: "VA05 overview: total count, open, in production, shipped, overdue.", category: "Customer", params: [] },
  { name: "factory_get_orders_at_risk", description: "At-risk customer orders near delivery date or overdue.", category: "Customer", params: [{ name: "daysAhead", required: false }] },
  // KPI (3)
  { name: "factory_get_customer_otd", description: "Overall on-time delivery rate across all customers.", category: "KPI", params: [] },
  { name: "factory_get_otd_statistics", description: "Detailed OTD statistics overall and per customer.", category: "KPI", params: [] },
  { name: "factory_get_monthly_revenue", description: "Monthly revenue from delivered customer orders.", category: "KPI", params: [] },
  // Maintenance (5)
  { name: "factory_get_open_notifications", description: "All open fault and maintenance notifications.", category: "Maintenance", params: [] },
  { name: "factory_get_maintenance_orders", description: "Maintenance orders, optionally filtered by status.", category: "Maintenance", params: [{ name: "status", required: false }] },
  { name: "factory_get_machine_reliability", description: "Reliability metrics: MTBF, MTTR, availability.", category: "Maintenance", params: [{ name: "machineNo", required: true }, { name: "daysBack", required: false }] },
  { name: "factory_get_maintenance_summary", description: "PM overview: open notifications, orders, MTBF/MTTR.", category: "Maintenance", params: [] },
  { name: "factory_get_downtime_report", description: "Downtime analysis with reason codes and duration.", category: "Maintenance", params: [{ name: "daysBack", required: false }] },
  // MRP (4)
  { name: "factory_get_md04", description: "Requirements/stock list (MD04) for a part, similar to SAP MD04.", category: "MRP", params: [{ name: "teilId", required: true }] },
  { name: "factory_get_md07", description: "All current shortages (MD07) — parts with stock deficits.", category: "MRP", params: [] },
  { name: "factory_get_availability_at_date", description: "Forecasts part availability at a specific date.", category: "MRP", params: [{ name: "teilId", required: true }, { name: "date", required: true }] },
  { name: "factory_get_baugruppen_shortages", description: "Shortages for assemblies (in-house production, not purchasable).", category: "MRP", params: [] },
  // OEE (4)
  { name: "factory_get_machine_oee", description: "OEE of a machine: availability x performance x quality.", category: "OEE", params: [{ name: "machineNo", required: true }, { name: "hours", required: false }] },
  { name: "factory_get_latest_oee", description: "Latest OEE values for all machines.", category: "OEE", params: [] },
  { name: "factory_get_production_history", description: "Production history: good parts, scrap, rework per hour.", category: "OEE", params: [{ name: "hours", required: false }] },
  { name: "factory_get_oee_summary", description: "OEE summary per machine: avg, min, max, scrap rate over a period. Sorted worst first.", category: "OEE", params: [{ name: "hours", required: false }] },
  { name: "factory_get_scrap_history", description: "Scrap history grouped by machine.", category: "OEE", params: [{ name: "hours", required: false }] },
  // Order (4)
  { name: "factory_get_work_order", description: "Details of a work order including material and capacity status.", category: "Order", params: [{ name: "orderNo", required: true }] },
  { name: "factory_get_machine_queue", description: "Machine queue: orders sorted by priority.", category: "Order", params: [{ name: "machineNo", required: true }] },
  { name: "factory_check_material_readiness", description: "Check material availability for a work order.", category: "Order", params: [{ name: "orderNo", required: true }] },
  { name: "factory_get_blocked_orders_count", description: "Number of blocked orders (material/capacity).", category: "Order", params: [] },
  // Purchase (3)
  { name: "factory_get_pending_purchases", description: "All open purchase orders with expected delivery dates.", category: "Purchase", params: [] },
  { name: "factory_get_supplier_for_material", description: "Supplier for a material with lead time and price.", category: "Purchase", params: [{ name: "teilId", required: true }] },
  { name: "factory_get_supplier_evaluation", description: "Supplier evaluation: delivery reliability, quality, pricing.", category: "Purchase", params: [{ name: "supplierId", required: false }] },
  // QMS (4)
  { name: "factory_get_spc_alarms", description: "Active SPC alarms with affected machines.", category: "QMS", params: [] },
  { name: "factory_get_calibration_due", description: "Measuring instruments with calibration due.", category: "QMS", params: [] },
  { name: "factory_get_quality_notifications", description: "Open quality notifications (complaints, internal defects).", category: "QMS", params: [] },
  { name: "factory_get_cpk_overview", description: "Process capability indices (Cpk) for all monitored characteristics.", category: "QMS", params: [{ name: "machineNo", required: false }] },
  // Stock (2)
  { name: "factory_get_stock_item", description: "Stock level of a material with reservations and availability.", category: "Stock", params: [{ name: "teilId", required: true }] },
  { name: "factory_get_low_stock_items", description: "Materials with low stock (below safety stock level).", category: "Stock", params: [] },
  { name: "factory_get_material_coverage", description: "Material coverage in days — which materials have the lowest reach based on stock vs. open demand.", category: "Stock", params: [] },
  // TMS (9)
  { name: "tms_get_status", description: "Status of all tools: wear, location, availability.", category: "TMS", params: [] },
  { name: "tms_get_machine_tools", description: "All tools currently at a machine.", category: "TMS", params: [{ name: "machine_no", required: true }] },
  { name: "tms_get_critical", description: "Tools with critical wear (>80%).", category: "TMS", params: [] },
  { name: "tms_replace_tool", description: "Replace a worn tool at a machine.", category: "TMS", params: [{ name: "machine_no", required: true }, { name: "old_tool_id", required: true }, { name: "new_tool_id", required: false }] },
  { name: "tms_get_replacements", description: "Available replacement tools for a tool type.", category: "TMS", params: [{ name: "werkzeug_id", required: true }] },
  { name: "tms_get_tools_for_article", description: "Tool list for an article — required tool types.", category: "TMS", params: [{ name: "article_no", required: true }] },
  { name: "tms_check_tool_availability", description: "Checks if a machine has all required tools for an article.", category: "TMS", params: [{ name: "machine_no", required: true }, { name: "article_no", required: true }] },
  { name: "tms_get_tool_changes", description: "Required tool changes for a changeover + additional setup time.", category: "TMS", params: [{ name: "machine_no", required: true }, { name: "article_no", required: true }] },
  { name: "tms_get_history", description: "Recent tool usages and replacements.", category: "TMS", params: [{ name: "limit", required: false }] },
  // SGM (5)
  { name: "sgm_get_process_data", description: "Injection molding process data (~97 parameters): temperatures, pressures, speeds.", category: "SGM", params: [{ name: "machine_no", required: true }, { name: "hours", required: false }] },
  { name: "sgm_get_process_trend", description: "Trend of a process parameter over time — drift detection.", category: "SGM", params: [{ name: "machine_no", required: true }, { name: "parameter", required: true }, { name: "hours", required: false }] },
  { name: "sgm_get_cavity_balance", description: "Cavity balance (pressure distribution) — detects uneven filling.", category: "SGM", params: [{ name: "machine_no", required: true }, { name: "shots", required: false }] },
  { name: "sgm_get_cavity_trend", description: "Trend of a cavity (hot runner temp, pressure) over time.", category: "SGM", params: [{ name: "machine_no", required: true }, { name: "cavity_nr", required: true }, { name: "hours", required: false }] },
  { name: "sgm_get_hourly_aggregates", description: "Hourly aggregates: averages, shot count, scrap rate.", category: "SGM", params: [{ name: "machine_no", required: true }, { name: "hours", required: false }] },
  // Assembly (14)
  { name: "montage_get_tms_status", description: "Status of all assembly tools: wear, station, availability.", category: "Assembly", params: [] },
  { name: "montage_get_critical_tools", description: "Assembly tools with critical wear (>80%).", category: "Assembly", params: [] },
  { name: "montage_get_station_tools", description: "All tools at an assembly station.", category: "Assembly", params: [{ name: "station_id", required: true }] },
  { name: "montage_get_replacements", description: "Replacement tools for an assembly tool type.", category: "Assembly", params: [{ name: "werkzeug_id", required: true }] },
  { name: "montage_replace_tool", description: "Replace a worn tool at an assembly station.", category: "Assembly", params: [{ name: "station_id", required: true }, { name: "old_tool_id", required: true }] },
  { name: "montage_get_tool_history", description: "Recent tool usages at assembly stations.", category: "Assembly", params: [{ name: "limit", required: false }] },
  { name: "montage_get_maintenance_summary", description: "Assembly line maintenance overview.", category: "Assembly", params: [] },
  { name: "montage_get_open_notifications", description: "Open fault/maintenance notifications for assembly lines.", category: "Assembly", params: [] },
  { name: "montage_get_open_orders", description: "Open maintenance orders for assembly lines.", category: "Assembly", params: [] },
  { name: "montage_get_station_reliability", description: "Reliability metrics: MTBF, MTTR, availability.", category: "Assembly", params: [{ name: "station_id", required: false }] },
  { name: "montage_get_due_plans", description: "Due maintenance plans for assembly lines.", category: "Assembly", params: [] },
  { name: "montage_get_oee", description: "OEE of an assembly line (availability, performance, quality).", category: "Assembly", params: [{ name: "linie_id", required: false }] },
  { name: "montage_get_prozessdaten", description: "Process data of an assembly station (parameters, targets, tolerances).", category: "Assembly", params: [{ name: "station_id", required: true }, { name: "limit", required: false }] },
  { name: "montage_get_bde", description: "Shop floor data: cycle times, good parts, NOK parts, fault reasons.", category: "Assembly", params: [{ name: "linie_id", required: false }, { name: "limit", required: false }] },
  // Energy (6)
  { name: "factory_get_energy_overview", description: "Energy consumption of all machines: current power draw, total kWh.", category: "Energy", params: [] },
  { name: "factory_get_machine_energy", description: "Energy consumption of a machine over time.", category: "Energy", params: [{ name: "machineNo", required: true }, { name: "hours", required: false }] },
  { name: "factory_get_energy_per_part", description: "kWh per good part for a machine.", category: "Energy", params: [{ name: "machineNo", required: true }, { name: "hours", required: false }] },
  { name: "factory_get_energy_costs", description: "Energy costs in EUR.", category: "Energy", params: [{ name: "pricePerKwh", required: false }, { name: "hours", required: false }] },
  { name: "factory_get_energy_trend", description: "Hourly power trend for a machine.", category: "Energy", params: [{ name: "machineNo", required: true }, { name: "hours", required: false }] },
  { name: "factory_get_base_load", description: "Base load vs. production load of all machines.", category: "Energy", params: [] },
  // Subcontracting (7)
  { name: "factory_get_fb_auftraege", description: "All subcontracting orders with status.", category: "Subcontracting", params: [{ name: "status", required: false }] },
  { name: "factory_get_fb_kapazitaet", description: "Capacity and utilization of subcontracting suppliers.", category: "Subcontracting", params: [] },
  { name: "factory_get_fb_versand", description: "Orders ready for shipment to supplier.", category: "Subcontracting", params: [] },
  { name: "factory_get_fb_wareneingang", description: "Orders with expected goods receipt.", category: "Subcontracting", params: [] },
  { name: "factory_get_fb_liefertreue", description: "Delivery reliability of subcontracting suppliers.", category: "Subcontracting", params: [] },
  { name: "factory_get_fb_queue", description: "Orders in queue by supplier.", category: "Subcontracting", params: [{ name: "lieferantId", required: false }] },
  { name: "factory_get_fb_bewertung", description: "Quality rating of subcontracting suppliers.", category: "Subcontracting", params: [] },
  // Pre-Assembly (4)
  { name: "montage_get_vormontage_status", description: "Status of pre-assembly cells VM-1, VM-2, VM-3.", category: "Pre-Assembly", params: [] },
  { name: "montage_get_vormontage_oee", description: "OEE of pre-assembly cells.", category: "Pre-Assembly", params: [{ name: "cell_id", required: false }] },
  { name: "montage_get_vormontage_buffer", description: "Buffer fill levels between pre-assembly and assembly lines.", category: "Pre-Assembly", params: [] },
  { name: "montage_get_vormontage_wartung", description: "Maintenance status of pre-assembly stations.", category: "Pre-Assembly", params: [] },
  // Test Field (4)
  { name: "montage_get_prueffeld_status", description: "Status of the test field (function test, leak test, burn-in).", category: "Test Field", params: [] },
  { name: "montage_get_prueffeld_ergebnisse", description: "Pass/fail rate of the test field.", category: "Test Field", params: [{ name: "hours", required: false }] },
  { name: "montage_get_prueffeld_queue", description: "Parts in the test field queue.", category: "Test Field", params: [] },
  { name: "montage_get_prueffeld_fehleranalyse", description: "Defect analysis by defect type and product.", category: "Test Field", params: [] },
  // History (6)
  { name: "history_get_trend", description: "Time-series data for a machine variable over configurable hours.", category: "History", params: [{ name: "machine", required: true }, { name: "variable", required: true }, { name: "hours", required: false }, { name: "limit", required: false }] },
  { name: "history_compare", description: "Compare same variable between two machines.", category: "History", params: [{ name: "machine_a", required: true }, { name: "machine_b", required: true }, { name: "variable", required: true }, { name: "hours", required: false }] },
  { name: "history_aggregate", description: "Aggregated values (AVG/MIN/MAX) per granularity.", category: "History", params: [{ name: "machine", required: true }, { name: "variable", required: true }, { name: "granularity", required: false }, { name: "hours", required: false }] },
  { name: "history_anomalies", description: "Find values deviating beyond N sigma from mean.", category: "History", params: [{ name: "machine", required: true }, { name: "variable", required: true }, { name: "hours", required: false }, { name: "sigma", required: false }] },
  { name: "history_machines", description: "List all machines with historian data and data point counts.", category: "History", params: [{ name: "hours", required: false }] },
  { name: "history_variables", description: "List all recorded variables for a specific machine.", category: "History", params: [{ name: "machine", required: true }] },
  // Knowledge Graph (12)
  { name: "kg_impact", description: "Trace downstream impact from a source node (up to 3 hops).", category: "Knowledge Graph", params: [{ name: "node_id", required: true }] },
  { name: "kg_path", description: "Find shortest path between two nodes.", category: "Knowledge Graph", params: [{ name: "from_id", required: true }, { name: "to_id", required: true }] },
  { name: "kg_neighbors", description: "Get all neighbor nodes within configurable depth.", category: "Knowledge Graph", params: [{ name: "node_id", required: true }, { name: "depth", required: false }] },
  { name: "kg_aggregate", description: "Aggregate numeric property across a label.", category: "Knowledge Graph", params: [{ name: "label", required: true }, { name: "property", required: true }] },
  { name: "kg_search", description: "Semantic search by natural language using vector embeddings.", category: "Knowledge Graph", params: [{ name: "query", required: true }, { name: "limit", required: false }, { name: "label_filter", required: false }] },
  { name: "kg_schema", description: "Get complete KG schema — labels, relationships, properties.", category: "Knowledge Graph", params: [] },
  { name: "kg_subgraph", description: "Extract subgraph around a node within radius.", category: "Knowledge Graph", params: [{ name: "node_id", required: true }, { name: "radius", required: false }] },
  { name: "kg_filter", description: "Filter nodes by label and property conditions.", category: "Knowledge Graph", params: [{ name: "label", required: true }, { name: "conditions", required: false }, { name: "limit", required: false }] },
  { name: "kg_query", description: "Run a read-only Cypher query against the Knowledge Graph.", category: "Knowledge Graph", params: [{ name: "cypher", required: true }, { name: "params", required: false }] },
  { name: "kg_stats", description: "Quick summary: total nodes, edges, top labels, top relationship types.", category: "Knowledge Graph", params: [] },
  { name: "kg_delivery_snapshot", description: "Delivery feasibility snapshot — orders with materials, stock, machine capacity, OEE, customer info.", category: "Knowledge Graph", params: [{ name: "days_ahead", required: false }] },
  { name: "kg_generate_chart", description: "Generate a Chart.js visualization from a natural language question about the KG.", category: "Knowledge Graph", params: [{ name: "question", required: true }] },
  // UNS (8)
  { name: "uns_list_machines", description: "List all machines currently publishing UNS data via MQTT.", category: "UNS", params: [] },
  { name: "uns_get_machine_status", description: "Get all current UNS values for a machine: BDE, ProcessData, OEE, Status.", category: "UNS", params: [{ name: "machine", required: true }] },
  { name: "uns_get_value", description: "Read a single UNS topic value by full topic path.", category: "UNS", params: [{ name: "topic", required: true }] },
  { name: "uns_get_category", description: "Get all values of a data category for a machine (BDE, ProcessData, QMS, WMS).", category: "UNS", params: [{ name: "machine", required: true }, { name: "category", required: true }] },
  { name: "uns_search_topics", description: "Search UNS topics by pattern with wildcards (* = single level, # = multi level).", category: "UNS", params: [{ name: "pattern", required: true }] },
  { name: "uns_get_alerts", description: "Show all UNS values with non-good quality (faults, warnings, bad readings).", category: "UNS", params: [] },
  { name: "uns_get_history", description: "Get last N values of a UNS topic from ring buffer — shows trend.", category: "UNS", params: [{ name: "topic", required: true }, { name: "count", required: false }] },
  { name: "uns_compare_machines", description: "Compare the same variable across multiple machines.", category: "UNS", params: [{ name: "machines", required: true }, { name: "variable", required: true }] },
  // Discovery (2)
  { name: "kg_discovered_machines", description: "All machines auto-discovered from MQTT UNS.", category: "Discovery", params: [] },
  { name: "kg_machine_sensors", description: "All sensors on a discovered machine with last values.", category: "Discovery", params: [{ name: "machine", required: true }] },
];
