import { WikiSection } from "@/components/wiki/WikiSection";
import { WikiCallout } from "@/components/wiki/WikiCallout";

export function GovernanceContent() {
  return (
    <>
      <WikiSection title="Overview">
        <p>
          The Governance system provides role-based access control (RBAC) for all
          MCP tool calls. Every tool invocation is classified by sensitivity,
          checked against the user&apos;s factory role, and logged in an immutable
          audit trail.
        </p>
        <p>
          This ensures that operators on the shop floor can only access tools
          appropriate to their role, while planners and quality engineers get
          broader access to analytical and management tools.
        </p>
      </WikiSection>

      <WikiSection title="Factory Roles">
        <p>
          Six predefined roles map to common manufacturing organizational
          structures:
        </p>
        <div className="mt-3 space-y-3">
          {[
            ["Operator", "Shop floor access: machine status, BDE entry, basic OEE queries"],
            ["Meister", "Shift lead access: production overview, quality alerts, tool management"],
            ["Planner", "Planning access: orders, scheduling, capacity, material management"],
            ["Quality Engineer", "Quality access: defect analysis, SPC, audit data, CAPA management"],
            ["Admin", "System administration: user management, configuration, system health"],
            ["Full Access", "Unrestricted access to all tools (development and demo use)"],
          ].map(([role, desc]) => (
            <div key={role} className="p-3 rounded border border-border bg-bg-surface-2">
              <code className="text-accent text-xs font-mono">{role}</code>
              <p className="mt-1 text-sm">{desc}</p>
            </div>
          ))}
        </div>
      </WikiSection>

      <WikiSection title="Tool Categories">
        <p>
          Tools are organized into functional categories that map to manufacturing
          domains:
        </p>
        <ul className="list-disc list-inside space-y-2 mt-2">
          <li>
            <strong>ERP</strong> &mdash; Production orders, customers, deliveries, BOM
          </li>
          <li>
            <strong>OEE</strong> &mdash; Machine performance, availability, quality metrics
          </li>
          <li>
            <strong>QMS</strong> &mdash; Defect reports, inspections, audits, CAPA
          </li>
          <li>
            <strong>TMS</strong> &mdash; Tool management, lifecycle, wear tracking
          </li>
          <li>
            <strong>KG</strong> &mdash; Knowledge Graph queries, impact analysis, chart generation
          </li>
          <li>
            <strong>UNS</strong> &mdash; Unified Namespace MQTT topics, live machine data
          </li>
          <li>
            <strong>History</strong> &mdash; Time-series queries, trend analysis, anomaly detection
          </li>
          <li>
            <strong>Maintenance</strong> &mdash; Work orders, preventive schedules, spare parts
          </li>
        </ul>
      </WikiSection>

      <WikiSection title="Tool Classification">
        <p>
          Every tool is automatically classified by the governance agent with a
          sensitivity level:
        </p>
        <div className="mt-3 space-y-2">
          {[
            ["low", "text-green-400", "Read-only queries, status checks, dashboard data"],
            ["medium", "text-yellow-400", "Analytical tools, report generation, data export"],
            ["high", "text-orange-400", "Write operations, configuration changes, order modifications"],
            ["critical", "text-red-400", "System administration, user management, destructive operations"],
          ].map(([level, color, desc]) => (
            <div key={level} className="flex items-center gap-3 text-sm">
              <code className={`${color} bg-accent/10 px-2 py-0.5 rounded text-xs font-mono min-w-[5rem] text-center`}>
                {level}
              </code>
              <span className="text-text-dim">{desc}</span>
            </div>
          ))}
        </div>
        <WikiCallout type="info">
          Tool classifications are auto-generated by the governance agent based on
          tool descriptions and parameters. Admins can override classifications in
          the Admin UI.
        </WikiCallout>
      </WikiSection>

      <WikiSection title="Audit Log">
        <p>
          Every MCP tool call is logged with full context for compliance and
          debugging:
        </p>
        <ul className="list-disc list-inside space-y-2 mt-2">
          <li>
            <strong>User</strong> &mdash; Authenticated user identity and assigned role
          </li>
          <li>
            <strong>Timestamp</strong> &mdash; ISO 8601 timestamp of the tool invocation
          </li>
          <li>
            <strong>Tool</strong> &mdash; Tool name, category, and sensitivity level
          </li>
          <li>
            <strong>Parameters</strong> &mdash; Full input parameters (sensitive fields redacted)
          </li>
          <li>
            <strong>Result</strong> &mdash; Success/failure status, execution time, error details
          </li>
          <li>
            <strong>Decision</strong> &mdash; Whether access was granted or denied, and the
            matching rule
          </li>
        </ul>
        <div className="mt-3 rounded-md border border-border bg-[#0d1117] p-4 font-mono text-xs text-gray-300 leading-relaxed">
          <div className="text-text-dim">{"// Example audit log entry"}</div>
          <div>{"{"}</div>
          <div>{"  user: 'meister@factory.de',"}</div>
          <div>{"  role: 'Meister',"}</div>
          <div>{"  tool: 'erp_get_production_orders',"}</div>
          <div>{"  category: 'ERP',"}</div>
          <div>{"  sensitivity: 'low',"}</div>
          <div>{"  decision: 'ALLOW',"}</div>
          <div>{"  duration_ms: 42,"}</div>
          <div>{"  timestamp: '2026-03-19T08:15:23Z'"}</div>
          <div>{"}"}</div>
        </div>
      </WikiSection>

      <WikiSection title="Admin UI">
        <p>
          The Governance Admin UI provides four tabs for managing access control:
        </p>
        <div className="mt-3 space-y-3">
          <div className="p-3 rounded border border-border bg-bg-surface-2">
            <code className="text-accent text-xs font-mono">Roles Tab</code>
            <p className="mt-1 text-sm">
              Create and edit factory roles. Assign tool categories and sensitivity
              thresholds to each role. Preview effective permissions.
            </p>
          </div>
          <div className="p-3 rounded border border-border bg-bg-surface-2">
            <code className="text-accent text-xs font-mono">Categories Tab</code>
            <p className="mt-1 text-sm">
              Manage tool categories. Group related tools, set default sensitivity
              levels, and configure category-level access rules.
            </p>
          </div>
          <div className="p-3 rounded border border-border bg-bg-surface-2">
            <code className="text-accent text-xs font-mono">Classifications Tab</code>
            <p className="mt-1 text-sm">
              Review and override auto-generated tool classifications. See which
              tools are assigned to which sensitivity level.
            </p>
          </div>
          <div className="p-3 rounded border border-border bg-bg-surface-2">
            <code className="text-accent text-xs font-mono">Audit Tab</code>
            <p className="mt-1 text-sm">
              Search and filter the audit log by user, role, tool, category, time
              range, and decision (allow/deny). Export to CSV.
            </p>
          </div>
        </div>
        <WikiCallout type="tip">
          The Admin UI is only accessible to users with the Admin or Full Access
          role. All admin actions are themselves audit-logged.
        </WikiCallout>
      </WikiSection>
    </>
  );
}
