FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY chat-space.html /usr/share/nginx/html/index.html
COPY chat-space.html /usr/share/nginx/html/chat-space.html
COPY chat.html /usr/share/nginx/html/chat.html
COPY chat_ts.html /usr/share/nginx/html/chat_ts.html
COPY divachat.html /usr/share/nginx/html/divachat.html
EXPOSE 80
